---

- name: Ensure MySQL database is present.
  mysql_db:
    name: "{{ waj_mysql_db_name }}"
    collation: "{{ waj_mysql_db_collation | default('utf8_general_ci') }}"
    encoding: "{{ waj_mysql_db_encoding | default('utf8') }}"
    # login_unix_socket: "{{ mysql_socket }}"
    state: "{{ waj_mysql_db_state | default('present') }}"

- name: Ensure MySQL user is present.
  mysql_user:
    name: "{{ waj_mysql_user_name }}"
    host: "{{ waj_mysql_user_host | default('localhost') }}"
    password: "{{ waj_mysql_user_password }}"
    priv: "{{ waj_mysql_user_priv | default('*.*:USAGE') }}"
    state: "{{ waj_mysql_user_state | default('present') }}"
    # login_unix_socket: "{{ mysql_socket }}"
    append_privs: "{{ waj_mysql_user_append_privs | default('no') }}"
    encrypted: "{{ waj_mysql_user_encrypted | default('no') }}"
  no_log: true

- name: Configure automysqlbackup
  replace:
    path: "/etc/default/automysqlbackup"
    regexp: "/etc/mysql/debian.cnf"
    replace: "{{ mysql_root_home }}/.my.cnf"