---
- name: Check if MySQL is already installed.
  stat:
    path: "/etc/init.d/{{ mysql_daemon }}"
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes
  when: not mysql_installed.stat.exists

- name: Determine required MySQL Python libraries.
  set_fact:
    deb_mysql_python_package: "{{ 'python3-mysqldb' if (ansible_facts.python.version.major | int) >= 3 else 'python-mysqldb' }}"

- name: Ensure MySQL Python libraries are installed.
  apt:
    name: "{{ deb_mysql_python_package }}"
    state: present

- name: Ensure MySQL packages are installed.
  apt:
    name: "{{ mysql_packages }}"
    state: present
  register: mysql_install_packages

# Because package install can auto-start MySQL, stop it before config tasks on first install.
- name: Ensure MySQL is stopped after initial install.
  service: "name={{ mysql_daemon }} state=stopped"
  when: not mysql_installed.stat.exists

- name: Get MySQL version.
  command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false
  check_mode: false
